- require:
    - com.foundationdb.sql.LayerInfoInterface
    - com.foundationdb.server.service.dxl.DXLService
    - com.foundationdb.server.service.stats.StatisticsService
    - com.foundationdb.server.service.jmx.JmxRegistryService
    - com.foundationdb.sql.pg.PostgresService
    - com.foundationdb.sql.embedded.EmbeddedJDBCService
    - com.foundationdb.server.service.log4jconfig.Log4JConfigurationService
    - com.foundationdb.server.service.monitor.MonitorService
    - com.foundationdb.server.service.is.BasicInfoSchemaTablesService
    - com.foundationdb.server.service.is.ServerSchemaTablesService
    - com.foundationdb.server.types.service.TypesRegistrySchemaTablesService
# Plugins
    - com.foundationdb.rest.RestService
# Uncomment for a simple UI
#    - com.foundationdb.sql.ui.SwingConsoleService
#- prioritize:
#    - com.foundationdb.sql.ui.SwingConsoleService

